//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace College.Areas.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manager
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
        public System.DateTime Birthday { get; set; }
        public int PhoneNumber { get; set; }
        public string Email { get; set; }
    }
}
